/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettingRouteImport } from './routes/_authenticated/setting'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedMyPrivilegesRouteImport } from './routes/_authenticated/myPrivileges'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedInvestmentsRouteImport } from './routes/_authenticated/investments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreditCardRouteImport } from './routes/_authenticated/creditCard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingRoute = AuthenticatedSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPrivilegesRoute =
  AuthenticatedMyPrivilegesRouteImport.update({
    id: '/myPrivileges',
    path: '/myPrivileges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestmentsRoute =
  AuthenticatedInvestmentsRouteImport.update({
    id: '/investments',
    path: '/investments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditCardRoute = AuthenticatedCreditCardRouteImport.update({
  id: '/creditCard',
  path: '/creditCard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/account': typeof AuthenticatedAccountRoute
  '/creditCard': typeof AuthenticatedCreditCardRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/investments': typeof AuthenticatedInvestmentsRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/myPrivileges': typeof AuthenticatedMyPrivilegesRoute
  '/services': typeof AuthenticatedServicesRoute
  '/setting': typeof AuthenticatedSettingRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
}
export interface FileRoutesByTo {
  '/account': typeof AuthenticatedAccountRoute
  '/creditCard': typeof AuthenticatedCreditCardRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/investments': typeof AuthenticatedInvestmentsRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/myPrivileges': typeof AuthenticatedMyPrivilegesRoute
  '/services': typeof AuthenticatedServicesRoute
  '/setting': typeof AuthenticatedSettingRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/creditCard': typeof AuthenticatedCreditCardRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/investments': typeof AuthenticatedInvestmentsRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/myPrivileges': typeof AuthenticatedMyPrivilegesRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/setting': typeof AuthenticatedSettingRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/creditCard'
    | '/dashboard'
    | '/investments'
    | '/loans'
    | '/myPrivileges'
    | '/services'
    | '/setting'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/creditCard'
    | '/dashboard'
    | '/investments'
    | '/loans'
    | '/myPrivileges'
    | '/services'
    | '/setting'
    | '/transactions'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/account'
    | '/_authenticated/creditCard'
    | '/_authenticated/dashboard'
    | '/_authenticated/investments'
    | '/_authenticated/loans'
    | '/_authenticated/myPrivileges'
    | '/_authenticated/services'
    | '/_authenticated/setting'
    | '/_authenticated/transactions'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setting': {
      id: '/_authenticated/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AuthenticatedSettingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/myPrivileges': {
      id: '/_authenticated/myPrivileges'
      path: '/myPrivileges'
      fullPath: '/myPrivileges'
      preLoaderRoute: typeof AuthenticatedMyPrivilegesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investments': {
      id: '/_authenticated/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AuthenticatedInvestmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creditCard': {
      id: '/_authenticated/creditCard'
      path: '/creditCard'
      fullPath: '/creditCard'
      preLoaderRoute: typeof AuthenticatedCreditCardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCreditCardRoute: typeof AuthenticatedCreditCardRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvestmentsRoute: typeof AuthenticatedInvestmentsRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedMyPrivilegesRoute: typeof AuthenticatedMyPrivilegesRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingRoute: typeof AuthenticatedSettingRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCreditCardRoute: AuthenticatedCreditCardRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvestmentsRoute: AuthenticatedInvestmentsRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedMyPrivilegesRoute: AuthenticatedMyPrivilegesRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingRoute: AuthenticatedSettingRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
